name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      
      - name: Firebase Debug Info
        run: |
          firebase --version
          firebase projects:list
          
    - name: Write service account key to file
  run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}" > firebase-key.json

- name: Set GOOGLE_APPLICATION_CREDENTIALS
  run: echo "GOOGLE_APPLICATION_CREDENTIALS=firebase-key.json" >> $GITHUB_ENV

- name: Deploy to Firebase Hosting
  run: firebase deploy --only hosting --project gen-lang-client-0814041184
