name: Firebase Debug

on:
  push:
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Dump Firebase Service Account JSON (Redacted)
        run: |
          echo "=== START OF SECRET ==="
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }}' | jq '. | {client_email, project_id, type}'
          echo "=== END OF SECRET ==="
