name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      
      - name: Firebase Debug Info
        run: |
          firebase --version
          firebase projects:list
          
      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: cd $GITHUB_WORKSPACE
    firebase deploy --only hosting --project gen-lang-client-0814041184
